import { defineConfig } from 'cypress'
import fs from 'fs-extra'

export default defineConfig({
  projectId: 'dg4gqg',
  viewportWidth: 1400,
  viewportHeight: 900,
  defaultCommandTimeout: 10000,
  requestTimeout: 10000,
  scrollBehavior: false,
  // To prevent browser out of memory, only keep one task in memory, https://blog.hao.dev/fixing-cypress-errors-part-1-chromium-out-of-memory-crashes
  numTestsKeptInMemory: 1,
  env: {
    // For cypress-image-diff-js to not delete snapshot in /cy/snapshot folder
    preserveOriginalScreenshot: true,
  },
  e2e: {
    baseUrl: 'http://localhost:8080/',
    experimentalRunAllSpecs: true,
    experimentalWebKitSupport: true,
    setupNodeEvents(on, config) {
      require('cypress-terminal-report/src/installLogsPrinter')(on)
      require('cypress-image-diff-js/dist/plugin')(on, config)

      on('after:run', () => {
        if (!fs.existsSync('./cypress-visual-screenshots/diff')) return

        // Copy diff image generated by cypress-image-diff-js to cy/screenshots folder
        for (const diffPath of fs.readdirSync('./cypress-visual-screenshots/diff')) {
          const specMatch = diffPath.match(/^[.\w]+.cy.ts/)
          if (!specMatch) continue
          const specName = specMatch[0]
          fs.copyFileSync(
            `cypress-visual-screenshots/diff/${diffPath}`,
            `cypress/screenshots/${specName}/${diffPath.replace('.png', '-diff.png')}`
          )
        }
      })
    },
  },
})
