/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AspectRatioSelector: typeof import('./components/panel-content/AspectRatioSelector.vue')['default']
    BgRemoveContainer: typeof import('./components/global/BgRemoveContainer.vue')['default']
    BottomPanel: typeof import('./components/BottomPanel.vue')['default']
    Btn: (typeof import('./components/global/Btn.vue'))['default']
    FeatureCard: typeof import('./components/home/FeatureCard.vue')['default']
    Fuck: typeof import('./components/Fuck.vue')['default']
    Headerbar: typeof import('./components/Headerbar.vue')['default']
    HelloWorld: (typeof import('./components/HelloWorld.vue'))['default']
    HomeTab: typeof import('./components/panel-content/HomeTab.vue')['default']
    IconCommunity: typeof import('./components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./components/icons/IconTooling.vue')['default']
    NuBtn: typeof import('./components/global/NuBtn.vue')['default']
    NuSvgIcon: typeof import('./components/global/NuSvgIcon.vue')['default']
    PinchableContainer: typeof import('./components/global/PinchableContainer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./components/global/SvgIcon.vue')['default']
    SvgIconTest: typeof import('./components/global/SvgIconTest.vue')['default']
    SvgTest: (typeof import('./components/SvgTest.vue'))['default']
    TestBtn: (typeof import('./components/TestBtn.vue'))['default']
    TheWelcome: (typeof import('./components/TheWelcome.vue'))['default']
    WelcomeItem: (typeof import('./components/WelcomeItem.vue'))['default']
  }
}
