/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('./components/accordion/Accordion.vue')['default']
    AspectRatioSelector: typeof import('./components/panel-content/AspectRatioSelector.vue')['default']
    BackBtn: typeof import('./components/global/BackBtn.vue')['default']
    BottomPanel: typeof import('./components/BottomPanel.vue')['default']
    CanvasSection: typeof import('./components/editor/CanvasSection.vue')['default']
    copy: typeof import('./components/panel-content/PromptArea copy.vue')['default']
    EditingOptions: typeof import('./components/panel-content/EditingOptions.vue')['default']
    FeatureCard: typeof import('./components/home/FeatureCard.vue')['default']
    Headerbar: typeof import('./components/Headerbar.vue')['default']
    HomeTab: typeof import('./components/panel-content/HomeTab.vue')['default']
    ModalInfo: typeof import('./components/panel-content/ModalInfo.vue')['default']
    ModalInfoo: typeof import('./components/panel-content/ModalInfoo.vue')['default']
    ModalTemplate: typeof import('./components/panel-content/ModalTemplate.vue')['default']
    NuBtn: typeof import('./components/global/NuBtn.vue')['default']
    NuSvgIcon: typeof import('./components/global/NuSvgIcon.vue')['default']
    PromptArea: typeof import('./components/panel-content/PromptArea.vue')['default']
    PropsSlider: typeof import('./components/global/PropsSlider.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollableContainer: typeof import('./components/global/ScrollableContainer.vue')['default']
    SvgIconTest: typeof import('./components/global/SvgIconTest.vue')['default']
    UseTapTransition: typeof import('./components/global/UseTapTransition.vue')['default']
  }
}
