/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AspectRatioSelector: typeof import('./components/panel-content/AspectRatioSelector.vue')['default']
    BackBtn: typeof import('./components/global/BackBtn.vue')['default']
    BottomPanel: typeof import('./components/BottomPanel.vue')['default']
    CanvasSection: typeof import('./components/editor/CanvasSection.vue')['default']
    CmBtn: typeof import('./components/global/CmBtn.vue')['default']
    CmSvgIcon: typeof import('./components/global/CmSvgIcon.vue')['default']
    EditingOptions: typeof import('./components/panel-content/EditingOptions.vue')['default']
    FeatureCard: typeof import('./components/home/FeatureCard.vue')['default']
    FunctionBar: typeof import('./components/global/FunctionBar.vue')['default']
    Headerbar: typeof import('./components/Headerbar.vue')['default']
    HighlightSection: typeof import('./components/home/HighlightSection.vue')['default']
    HomeTab: typeof import('./components/panel-content/HomeTab.vue')['default']
    ImgSelector: typeof import('./components/global/ImgSelector.vue')['default']
    LazyLoad: typeof import('./components/global/LazyLoad.vue')['default']
    ModalTemplate: typeof import('./components/panel-content/ModalTemplate.vue')['default']
    ObserverSentinel: typeof import('./components/global/ObserverSentinel.vue')['default']
    PromptArea: typeof import('./components/panel-content/PromptArea.vue')['default']
    PropsSlider: typeof import('./components/global/PropsSlider.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollableContainer: typeof import('./components/global/ScrollableContainer.vue')['default']
    SelectionOptions: typeof import('./components/panel-content/SelectionOptions.vue')['default']
    SidebarTabs: typeof import('./components/editor/SidebarTabs.vue')['default']
    SvgIconTest: typeof import('./components/global/SvgIconTest.vue')['default']
    UseTapTransition: typeof import('./components/global/UseTapTransition.vue')['default']
  }
}
