/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActionSheet: typeof import('./components/global/ActionSheet.vue')['default']
    AspectRatioSelector: typeof import('./components/panel-content/AspectRatioSelector.vue')['default']
    BackBtn: typeof import('./components/global/BackBtn.vue')['default']
    BottomPanel: typeof import('./components/BottomPanel.vue')['default']
    BrushOptions: typeof import('./components/panel-content/BrushOptions.vue')['default']
    CanvasOptions: typeof import('./components/panel-content/CanvasOptions.vue')['default']
    CanvasResizer: typeof import('./components/editor/CanvasResizer.vue')['default']
    CanvasSection: typeof import('./components/editor/CanvasSection.vue')['default']
    CompareImage: typeof import('./components/global/CompareImage.vue')['default']
    FeatureCard: typeof import('./components/home/FeatureCard.vue')['default']
    FooterBar: typeof import('./components/panel-content/FooterBar.vue')['default']
    FooterTabs: typeof import('./components/panel-content/FooterTabs.vue')['default']
    FunctionBar: typeof import('./components/global/FunctionBar.vue')['default']
    GenResult: typeof import('./components/panel-content/GenResult.vue')['default']
    Headerbar: typeof import('./components/Headerbar.vue')['default']
    HiddenMessageTutorial: typeof import('./components/tutorial/HiddenMessageTutorial.vue')['default']
    HighlightSection: typeof import('./components/home/HighlightSection.vue')['default']
    HomeTab: typeof import('./components/panel-content/HomeTab.vue')['default']
    ImgSelector: typeof import('./components/global/ImgSelector.vue')['default']
    MobilePanel: typeof import('./components/panel-content/MobilePanel.vue')['default']
    ModalTemplate: typeof import('./components/panel-content/ModalTemplate.vue')['default']
    ModalTemplateCm: typeof import('./components/panel-content/ModalTemplateCm.vue')['default']
    PanelColor: typeof import('./components/editor/panelMobile/PanelColor.vue')['default']
    PanelDescription: typeof import('./components/panel-content/PanelDescription.vue')['default']
    PanelLogin: typeof import('./components/editor/panelMobile/PanelLogin.vue')['default']
    Popup: typeof import('./components/popup/Popup.vue')['default']
    PowerfulFillTutorial: typeof import('./components/tutorial/PowerfulFillTutorial.vue')['default']
    PromptArea: typeof import('./components/panel-content/PromptArea.vue')['default']
    PropsSlider: typeof import('./components/global/PropsSlider.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SavingOptions: typeof import('./components/panel-content/SavingOptions.vue')['default']
    SavingTab: typeof import('./components/panel-content/SavingTab.vue')['default']
    ScrollableContainer: typeof import('./components/global/ScrollableContainer.vue')['default']
    SelectionOptions: typeof import('./components/panel-content/SelectionOptions.vue')['default']
    SidebarTabs: typeof import('./components/editor/SidebarTabs.vue')['default']
    SubDesignDetail: typeof import('./components/mydesign/SubDesignDetail.vue')['default']
    SubDesignView: typeof import('./components/mydesign/SubDesignView.vue')['default']
    SvgIconTest: typeof import('./components/global/SvgIconTest.vue')['default']
    Tutorial: typeof import('./components/tutorial/Tutorial.vue')['default']
  }
}
