/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Btn: typeof import('./components/Btn.vue')['default']
    Checkbox: typeof import('./components/Checkbox.vue')['default']
    CollapseTitle: typeof import('./components/CollapseTitle.vue')['default']
    ColorBtn: typeof import('./components/ColorBtn.vue')['default']
    Dropdown: typeof import('./components/Dropdown.vue')['default']
    ImageCarousel: typeof import('./components/ImageCarousel.vue')['default']
    MarkerIcon: typeof import('./components/MarkerIcon.vue')['default']
    PropertyBar: typeof import('./components/PropertyBar.vue')['default']
    RadioBtn: typeof import('./components/RadioBtn.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./components/SvgIcon.vue')['default']
    Test: typeof import('./components/Test.vue')['default']
    ToggleBtn: typeof import('./components/ToggleBtn.vue')['default']
    Url: typeof import('./components/Url.vue')['default']
  }
}
